version: '3'

services:
  app:
    build: './app'
    volumes:
      - './app:/app'
    ports:
      - '80:80'
    environment:
      # Make sure this line is commented before pushing to production!
      - 'FLASK_ENV=development'
      - 'FLASK_APP=main.py'
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: 'python main.py'
    depends_on:
      - database
  database:
    build: './database'
